//
// Created by salah elsayed on 5/11/2024.
//

#ifndef HOPSITAL_MANAGEMENT_SYSTEM_CUSTOMPRIORITYQUEUE_H
#define HOPSITAL_MANAGEMENT_SYSTEM_CUSTOMPRIORITYQUEUE_H

#endif //HOPSITAL_MANAGEMENT_SYSTEM_CUSTOMPRIORITYQUEUE_H
